In [2]:
print("NUMPY")

NUMPY


In [3]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [5]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [6]:
arr3=np.arange(0,10,1).reshape(2,5)
print(arr3)
print(arr3.shape)
print(arr3.ndim)
print(arr3.size)
print(arr3.dtype)
print(arr3.itemsize)


[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
2
10
int64
8


In [7]:
np.ones([2,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
#numpy vectorised operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
print("Addition",arr1+arr2)
print("Addition",arr1-arr2)
print("Addition",arr1*arr2)
print("Addition",arr1/arr2)



Addition [11 22 33 44 55]
Addition [ -9 -18 -27 -36 -45]
Addition [ 10  40  90 160 250]
Addition [0.1 0.1 0.1 0.1 0.1]


In [9]:
#universal function
arr4=np.array([2,3,4,5,6])
print(np.sqrt(arr4))
print(np.exp(arr4))
print(np.sin(arr4))
print(np.log(arr4))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [21]:
#array slicing and indexing
arr5=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr5)
print("--------------")
print(arr5[0])
print(arr5[0][0])
print(arr5[0][1])
print(arr5[1][1])
print(arr5[1:])
print(arr5[1:,2:])
print(arr5[0:2,2:])
print("--------------")

print(arr5[0:2,2:])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
--------------
[1 2 3 4 5]
1
2
7
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 8  9 10]
 [13 14 15]]
[[ 3  4  5]
 [ 8  9 10]]
--------------
[[ 3  4  5]
 [ 8  9 10]]


In [11]:
#data operation

data=np.array([1,2,3,4,5,6,7,8,9])
data[(data>5) & (data< 9)]


array([6, 7, 8])

In [12]:
#normalization
print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.var(data))

5.0
5.0
2.581988897471611
6.666666666666667
